# Import

In [41]:
import numpy as np
import pandas as pd
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

# Datasource
https://docs.google.com/document/d/1B3Itxfko-DzyzQlF4_Qc73aSTrcPyLpaySRRyD7-EY0/edit?tab=t.0

In [2]:
df = pd.read_csv("../database/BKSPublic.csv")
pd.set_option("display.max_info_columns", df.shape[1])

/tmp/ipykernel_1417867/1635701306.py:1: DtypeWarning: Columns (0: Do you get mood-based PMS symptoms during your menstrual cycle?, 1: Can you have vaginal orgasms *without* clitoral stimulation? (hy7nsai), 2: "In general, casual sexual hookups have been a ___ experience for me" (ytp3gfm), 3: "In general, when my romantic relationships end, who initiates the breakup?" (y33ksrt), 4: "I usually don't leave romantic relationships unless there's a very serious violation" (b7gzhvz), 5: Are you on hormonal birth control? This is the pill or any hormonal implant (pbj1u8c), 6: Where are you currently at in your menstrual cycle? Options are based on a typical 28 day cycle, but cycle length can change (7ok2l1v), 7: Are you currently experiencing PMS symptoms? (g953661), 8: Do you have baby fever? (9stu9yy)) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../database/BKSPublic.csv")

## Review Schema

In [3]:
# df.info(verbose=True, show_counts=True)
list(df.columns)

['biomale',
 'age',
 'As an adult, have you been the victim of sexual assault? (ld0srat)',
 'At what age did you first begin (at least semiregularly) masturbating?',
 'Personally, your preferred relationship style is: (4jib23m)',
 'sexcount',
 'Have you ever had a sexual experience with someone else who did not want the experience? (2zafc2j)',
 'How "sexually liberated" was your upbringing? (fs700v2)',
 'From the ages of 0-14, how often were you spanked as a form of discipline? (p957nyk)',
 'opennessvariable',
 'consciensiousnessvariable',
 'extroversionvariable',
 'neuroticismvariable',
 'agreeablenessvariable',
 'powerlessnessvariable',
 'TotalMentalIllness',
 'Compared to other people of your same gender and age range, you are (yh6d44s)',
 'youfeelmost',
 'Totalyoufeel',
 'otherfeel1most',
 'Totalotherfeel1',
 'Your sexual interests feel (44qhm16)',
 'pornhabit',
 'animated',
 'written',
 'violentporn',
 '"I am ashamed or embarrassed about at least some of what arouses me" (7cw1ziu)',
 '"Engaging with or fantasizing about what arouses me feels therapeutic or healing to me" (vmq8jqw)',
 '"I can get aroused by a partner doing what I like, even if I know they aren\'t aroused by it themselves" (aw1a1ss)',
 '"I\'ve acted upon or experimented with all the things that arouse me" (41kpfir)',
 'Have you paid for porn/erotic content? (pnltks8)',
 '"In general, on average, the optimal amount of consent in my preferred erotic scenarios is:" (b0ukpvo)',
 'Which describes you best? (cvc5b81)',
 '"I sometimes find people who have clearly reached sexual maturity, but are not yet adults (e.g., ages 13-17), to be sexually attractive" (kbpolw9)',
 'In scenarios you find erotic, you tend to identify with (or imagine being): (irv6czg)',
 'allrollidentity',
 '"I find it erotic when two people of the opposite gender to me sexually interact with each other" (fbqcymm)',
 'You ______ what arouses you (7mz0awx)',
 'knowwhatarousesyou',
 'In general, the most erotic scenarios are: (6e7lhil)',
 'highenergy',
 'cunnilingus',
 '"I find dirtytalking erotic" (947wne3)',
 '"I find the thought of existing (in *nonsexual* situations) as a biological *female* to be erotic" (6w84yry)',
 '"I find the thought of existing (in *nonsexual* situations) as a biological *male* to be erotic" (l7vpprx)',
 'Do you feel as though you\'ve "induced" new fetishes into yourself through the use of porn or erotic content, that otherwise would not have existed for you?',
 'inducefetish',
 'Which of the following sexual positions do you find significantly erotic?',
 'Which of the following sex acts do you find significantly erotic?',
 'Totalsexacts',
 'Of these options, which one is the most erotic? (s4xytoy)',
 'Totalfetish1',
 'Uncommon things: Check all the following categories that contain a thing that arouses you.',
 'Of these options, which one is the most erotic? (i73h77h)',
 'Totalfetish2',
 '"I find age-related things (beyond "normal" stuff like being attracted to people your own age) to be:" (92qqx0)',
 'secretions',
 'How old were you when you first experienced sexual interest in bodily-secretions? (i2kfd9)',
 'Which of the following bodily secretions do you find erotic?',
 'Of these options, which one is the most erotic? (i73h77k)',
 'Totalsecretions',
 'For breast milk, which of the following do you find erotic?',
 'For precum, which of the following do you find erotic?',
 'For saliva, which of the following do you find erotic?',
 'For squirt, which of the following do you find erotic?',
 'For sweat, which of the following do you find erotic?',
 'For urine, which of the following do you find erotic?',
 'Select all body parts you find significantly erotic',
 'Of these options, which one is the most erotic? (i73h77m)',
 'Totalbodyparts',
 'How old were you when you first experienced interest in specific body parts (not including standard sexual body parts like breasts or genitals)? (71x4a7w)',
 'lightbondage',
 'mediumbondage',
 'extremebondage',
 'In general, I prefer when the person in bondage is',
 'Which of the following do you find to be erotic?',
 'bondagemost',
 'Totalbondage',
 'How old were you when you first experienced sexual interest in bondage? (tdxu7cp)',
 'clothing',
 'How old were you when you first experienced interest in clothing related sexual interests? (4kl54pc)',
 'whowears',
 'Which of the following do you find erotic? (fv0xaot)',
 'Of these options, which one is the most erotic? (i73h77o)',
 'Totalclothingitems',
 'eagerness',
 'How old were you when you first experienced interest in eagerness related sexual interests? (twg3prj)',
 'worshipped',
 'worshipping',
 'teasing',
 'frustration',
 'Of these options, which one is the most erotic? (35jn7ei)',
 'Totaleager2',
 'exhibitionself',
 'exhibitionother',
 'voyeurself',
 'voyeurother',
 'How old were you when you first experienced sexual interest in exhibitionism or voyeurism? (xwggkkr)',
 'genderplay',
 'How old were you when you first experienced interest in genderplay related sexual interests? (3yixh1c)',
 'futa',
 '"I find it most erotic when the subject of my genderplay interest is:"',
 'Which of the following do you find erotic? (lb02f7w)',
 'Totalgenderplay2',
 'multiplepartners',
 'How old were you when you first experienced sexual interest in multiple partners or related scenarios? (hz27wpx)',
 'Of these options, which one is the most erotic? (35jn7ej)',
 'gentleness',
 'How old were you when you first experienced interest in gentleness related sexual interests? (j6jn9rl)',
 'Which of the following do you find erotic? (88ox5nl)',
 'Which of the following do you find erotic? (vqogs86)',
 'Of these options, which one is the most erotic? (35jn7eo)',
 'Totalmultiplepartners2',
 'Of these options, which one is the most erotic? (35jn7ek)',
 'gentleness2most',
 'Totalgentleness2',
 'nonconsent',
 'incest',
 'How old were you when you first experienced interest in incest? (9f6vg9x)',
 'How old were you when you first experienced sexual interest in nonconsent? (bx4o14o)',
 'Which of the following pairings do you find erotic?',
 'For sibling incest fantasies, which is your preferred pairing',
 'For aunt/uncle, niece/nephew incest fantasies, which is your preferred pairing',
 'mentalalteration',
 'Of these options, which one is the most erotic? (35jn7ew)',
 'nonconsent1most',
 'Totalnonconsent1',
 'powerdynamic',
 'How old were you when you first experienced sexual interest in power dynamics? (enrhyeb)',
 'When it comes to power dynamics, you tend to prefer scenarios that are more (xjfb7yy)',
 '"I find primal play to be:" (9rncgqc)',
 'obedience',
 'mindbreak',
 'masterslave',
 'mythical',
 'How old were you when you first experienced sexual interest in mythical creatures? (xfj2rdq)',
 'fulltimepower',
 'Of these options, which one is the most erotic? (35jn7ep)',
 'Totalmythical2',
 'objects',
 'How old were you when you first experienced sexual interest in your preferred object/objects? (3vnq7jt)',
 'Of these options, which one is the most erotic? (35jn7ex)',
 'Totalobjects2',
 'Of these options, which one is the most erotic? (35jn7ey)',
 'powerdynamic2most',
 'Totalpowerdynamic2',
 'roles',
 'How old were you when you first experienced sexual interest in specific roles? (ce5t067)',
 'Which of the following categories contains things you find erotic?',
 'Which of the following roles are erotic?',
 'Of these options, which one is the most erotic? (35jn7f0)',
 'Totalprofession',
 'pregnancy',
 'How old were you when you first experienced interest in pregnancy related sexual interests? (c2yvk62)',
 'Which of the following do you find erotic? (9d7qzaw)',
 'Which of the following is erotic?',
 'Of these options, which one is the most erotic? (35jn7ez)',
 'pregnancy2most',
 'Totalpregnancy2',
 'Which of the following do you find erotic? (9fkr5dx)',
 'Of these options, which one is the most erotic? (35jn7f1)',
 'Totalsexyrace',
 'sensory',
 'How old were you when you first experienced interest in sensory related sexual interests? (yg5rwaa)',
 'toys',
 'How old were you when you first experienced interest in scenarios involving sex toys? (iob8ewb)',
 'Which of the following sensations do you find erotic?',
 'Of these options, which one is the most erotic? (35jn7f3)',
 'Totalsensory2',
 'Of these options, which one is the most erotic? (35jn7f4)',
 'toys2most',
 'Totaltoys2',
 'transform',
 'How old were you when you first experienced interest in transformation related sexual interests? (ju7swdc)',
 '"I find situations erotic where transformations are ___" (d14kddh)',
 'Which of the following categories of transformations do you find erotic?',
 'Totaltransform1',
 'For general body transformation, which of the following is erotic?',
 'Which of the following is the most severe for you? (trspees)',
 'Check all that apply: Scenarios you find erotic tend to involve *you* feeling',
 'Check all that apply: Scenarios you find erotic tend to involve *the other person/people/creatures* feeling',
 '"I find the thought of masturbating alone as a biological female, to be erotic" (sgdpy8l)',
 '"I find the thought of masturbating alone as a biological male, to be erotic" (guwym9g)',
 'Your preferred breast size in a partner is: (dnuiinj)',
 'Common things: Check all the following categories that contain a thing that arouses you.',
 'abnormalbody',
 'How old were you when you first experienced interest in abnormal body/body part-related things? (si89mua)',
 'For Which of the following categories of abnormal body states do you find erotic?',
 'Of these options, which one is the most erotic? (i73h77l)',
 'Totalbodypartsabnormal',
 'Which body parts are most erotic when giant/oversized?',
 'Which body parts are most erotic when extremely small?',
 'genderswapped',
 'For Which of the following categories of genderswapped body states do you find erotic?',
 '"It\'s most erotic when the altered body is" (wdflfgk)',
 'How old were you when you first experienced interest in age-related sexual interests? (489pmk6)',
 'agegap',
 'older',
 'progression',
 'regression',
 'cgl',
 'brutality',
 'How old were you when you first experienced interest in brutality-related sexual interests? (5rsjhm2)',
 'For parent/child incest fantasies, which are your preferred pairings',
 'Totalincest3',
 'gratification',
 'badends',
 'Which of the following do you find erotic? (ovb55gx)',
 'Of these options, which one is the most erotic? (i73h77n)',
 'Totalbrutal2',
 'humiliation',
 'How old were you when you first experienced interest in humiliation related sexual interests? (jebtk3s)',
 'In general, you find it most erotic when the subject of humiliation is:',
 'Of these options, which one is the most erotic? (35jn7el)',
 'humiliation2most',
 'Totalhumiliation2',
 'How old were you when you first experienced sexual interest in mental alteration? (nesc17f)',
 'You prefer it when the mentally altered person is:',
 'Which of the following types of mental alteration do you find erotic?',
 'Of these options, which one is the most erotic? (35jn7en)',
 'mentalalteration2most',
 'Totalmentalalteration2',
 'In erotic scenarios involving nonconsent, you generally prefer when the nonconsenting person is:',
 'vore',
 'How old were you when you first experienced interest in vore related sexual interests? (58x0gp5)',
 'What kind of vore do you find erotic?',
 'You find vore in which orifices to be erotic?',
 'bestiality',
 'How old were you when you first experienced interest in bestiality/creatures-related sexual interests? (w3xlgsv)',
 'penetration',
 'penetration2',
 'oralsexanimal',
 'oralsexanimal2',
 'Of these options, which one is the most erotic? (i73h77i)',
 'Totalanimals',
 'When it comes to bestiality, which of the following creatures do you find erotic?',
 'animals2',
 'Of these options, which one is the most erotic? (i73h77j)',
 'Totalanimals2',
 'Which of the following do you find erotic? (ymvkzuu)',
 'For blood (menstrual), which of the following do you find erotic?',
 'sadomasochism',
 'How old were you when you first experienced sexual interest in sadomasochism? (zh8c32k)',
 'receivepain',
 'givepain',
 'spanking',
 'How important is it that the pain is also sexually gratifying to the recipient? (b31aufk)',
 '"I find psychological pain/torture to be:" (9hy7wy3)',
 'Which of the following types of sadomasochism do you find erotic?"',
 'Of these options, which one is the most erotic? (35jn7f2)',
 'Totalsadomasochism1',
 '"Scenarios where pain is given to genitals are arousing to me" (bobe874)',
 '"In general, I prefer scenarios where the intensity of the pain is:" (m73c3q1)',
 '"In general, I prefer scenarios where receiver of the pain is:" (8r5zld8)',
 'creepy',
 'How old were you when you first experienced interest in creepy/horror related sexual interests? (y9cxruq)',
 'Which of the following do you find erotic? (afadhb)',
 'Of these options, which one is the most erotic? (i73h77p)',
 'Totalcreep2',
 'dirty',
 'How old were you when you first experienced interest in dirtiness related sexual interests? (l7wbfjh)',
 'Which of the following disgust-oriented things do you find erotic?',
 'Of these options, which one is the most erotic? (35jn7eh)',
 'Totaldirty2',
 'Which of the following do you find erotic? (yftwuzf)',
 'My erotic fantasies involving toys typically involve ____ using the toys',
 'The type of erotic content you prefer tends to be more (2y636ej)',
 'The type of erotic content you prefer tends to be: (f98tjn5)',
 '"If my partner is aroused by something, I can also be aroused by it, even if I don\'t normally find it erotic" (j5yb5lu)',
 "If you tried very hard, could you stop being aroused by something you're into? (7lgg41e)",
 'totalfetishcategory',
 'In erotic scenarios involving age gaps, I prefer to be ____ (6njm5tr)',
 '"I find {bodypartsmost}:" (xw7vr7a)',
 'Which of the following do you find erotic, in the context of humiliation?',
 'Which of the following do you find erotic? (46pfeif)',
 'Which of the following messiness do you find erotic?',
 'Of these options, which one is the most erotic? (35jn7em)',
 'For grandparent/grandchild incest fantasies, which is your preferred pairing',
 'Which of the following drugs are erotic in sexual situations?',
 'Which of the following nonconsent scenarios do you find erotic?',
 'For scat (poop), which of the following do you find erotic?',
 'For blood (normal), which of the following do you find erotic?',
 "When it comes to necrophilia, it's most erotic when your role is:",
 'When it comes to necrophilia, you generally prefer fantasies where the dead body is:',
 'For vomit, which of the following do you find erotic?',
 'Which body parts are most erotic when extremely huge?',
 'For animal transformations, you prefer when the final result is ____? (yta91wx)',
 'For animal transformations, which of the following are the most erotic to you?',
 'Totaltransform2',
 'For smegma, which of the following do you find erotic?',
 'How honest were you when answering this survey? (g1vao1y)',
 'Which of the following do you find erotic? (npcvctu)',
 '"I find cunnilingus:" (jn2b355)',
 '"I find blowjobs:" (yuc275j)',
 '"I find anal sex (with a penis or penile toy):" (jhvha2f)',
 'normalsex',
 "In general, it's most erotic when _____ wears the clothing you find erotic (eowvxbs)",
 '"I find scenarios where I eagerly beg others to be:" (jvrbyep)',
 '"I find scenarios where others eagerly beg me to be:" (stmm5eg)',
 'marriage100blood',
 'Which of the following do you find erotic? (w1qo1g1)',
 'Which of the following do you find erotic? (5j281rq)',
 'Of these options, which one is the most erotic? (35jn7eg)',
 'Which of the following do you find erotic? (lfolao)',
 'appearance',
 'How old were you when you first experienced interest in your appearance-based sexual interests? (6qqg60a)',
 'Which of the following body weights do you find most erotic? (1jq57nf)',
 'ascore',
 'Which of the following body modifications do you find significantly erotic?',
 'Which of the following body types do you find significantly erotic?',
 "You're more sexually attracted to people whose gender identity ____ match their genitals (5b30vz2)",
 'How much of the porn or erotica you watch is violent? (joz3g52)',
 'At what age did you begin watching porn or reading erotic content at least semiregularly? (ugf1hyy)',
 'Which of the following do you find erotic? (32snt5e)',
 'When it comes to body horror, which of the following are erotic?',
 'Totalbodyhorror',
 'For male ejaculate, which of the following do you find erotic?',
 '"I am aroused by being dominant in sexual interactions" (6w3xquw)',
 '"I am aroused by being submissive in sexual interactions" (xem7hbu)',
 'Do you get mood-based PMS symptoms during your menstrual cycle?',
 'supernatural',
 '"I\'ve experienced a lot of sexual harrassment" (3knd12d)',
 'Which of the following do you find erotic? (26qr0sp)',
 'Which of the following do you find erotic? (yf0rmix)',
 'Which of the following do you find erotic? (wddo7ee)',
 'Which of the following do you find erotic? (zewlx2)',
 'Which of the following do you find erotic? (mfc7eve)',
 'Which of the following do you find erotic? (twppkp3)',
 'Which of the following do you find erotic? (u661iml)',
 'Which of the following do you find erotic? (9kmxhci)',
 'Which of the following do you find erotic? (fnwke2d)',
 'Which of the following do you find erotic? (g5qw0tc)',
 'Which of the following do you find erotic? (m66m8ix)',
 'Which of the following do you find erotic? (rhb3fup)',
 'Which of the following do you find erotic? (3hof3bj)',
 'Which of the following do you find erotic? (5mhacm7)',
 'Which of the following do you find erotic? (xhe2co5)',
 'Which of the following do you find erotic? (uju0gwc)',
 '"I find personal freeuse dynamics, arrangements where one partner can sexually "use" the other without asking or negotiating, to be erotic" (kspot4h)',
 'Can you have vaginal orgasms *without* clitoral stimulation? (hy7nsai)',
 '"In general, casual sexual hookups have been a ___ experience for me" (ytp3gfm)',
 '"In general, when my romantic relationships end, who initiates the breakup?" (y33ksrt)',
 '"I usually don\'t leave romantic relationships unless there\'s a very serious violation" (b7gzhvz)',
 'Getting catcalled on the street (or the thought of getting catcalled) feels more: (3qh0yh8)',
 'You find raceplay to be: (fkk3ykn)',
 'Are you on hormonal birth control? This is the pill or any hormonal implant (pbj1u8c)',
 'Which of the following do you find erotic? (a1m9v6u)',
 'Where are you currently at in your menstrual cycle? Options are based on a typical 28 day cycle, but cycle length can change (7ok2l1v)',
 'When I picture myself with a nude male body, I find this: (dl5zw4l)',
 'When I picture myself as having a nude female body, I find this: (yqi5pre)',
 'When I picture my own nude female breasts, buttocks, legs, or genitals, I find this: (qkw5ssz)',
 'The thought of someone else admiring me while I am a woman in the nude is: (yf7onjn)',
 'When I picture my own nude male buttocks, legs, or genitals, I find this: (f77m7qu)',
 'The thought of someone else admiring me while I am a man in the nude is: (g219v7x)',
 'How horny have you been in the last 24 hours? (2hyrmvh)',
 'How horny are you right now? (1jtj2nx)',
 'Are you currently experiencing PMS symptoms? (g953661)',
 '"To what extent do you agree with this statement: I am a narcissist. (1bqtk47)',
 'Do you have baby fever? (9stu9yy)',
 'bmi',
 'bondageaverage',
 'straightness',
 'politics',
 'childhood_adversity',
 'childhood_gender_tolerance']

# EDA
- arousalScale = [["Not arousing", 0], ["Slightly arousing", 1], ["Somewhat arousing", 2], ["Moderately arousing", 3], ["Very arousing", 5], ["Extremely arousing", 8]]

## Erotic: Action & Roles

In [4]:
df[['Of these options, which one is the most erotic? (35jn7ei)']].value_counts()

Of these options, which one is the most erotic? (35jn7ei)
Affection                                                    2211
Cuddling                                                     1730
Romance                                                      1625
Clear, enthusiastic consent                                  1404
Caretaker/caretakee dynamics                                  664
Therapeutic sexual experiences                                358
Sensual healing                                               189
Tantra                                                        167
Energy work                                                    50
Name: count, dtype: int64

### Actions

In [5]:
df[['Of these options, which one is the most erotic? (35jn7ei)']].value_counts()

Of these options, which one is the most erotic? (35jn7ei)
Affection                                                    2211
Cuddling                                                     1730
Romance                                                      1625
Clear, enthusiastic consent                                  1404
Caretaker/caretakee dynamics                                  664
Therapeutic sexual experiences                                358
Sensual healing                                               189
Tantra                                                        167
Energy work                                                    50
Name: count, dtype: int64

In [6]:
df[['Which of the following do you find erotic? (vqogs86)']].value_counts()

Which of the following do you find erotic? (vqogs86)
Clear, enthusiastic consent,Cuddling,Affection,Romance                                                                                                   781
Clear, enthusiastic consent,Cuddling,Affection,Romance,Caretaker/caretakee dynamics                                                                      252
Cuddling,Affection,Romance                                                                                                                               241
Clear, enthusiastic consent,Cuddling,Affection,Romance,Therapeutic sexual experiences                                                                    237
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance                                                                                   234
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences                                                    221
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                       204
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics    173
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics           121
Clear, enthusiastic consent,Cuddling,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                       115
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Caretaker/caretakee dynamics                                                      107
Clear, enthusiastic consent,Affection,Romance                                                                                                             88
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Energy work                                         78
Clear, enthusiastic consent,Cuddling,Romance                                                                                                              73
Affection,Romance                                                                                                                                         64
Clear, enthusiastic consent,Cuddling,Affection                                                                                                            64
Cuddling,Romance                                                                                                                                          58
Cuddling,Affection,Romance,Caretaker/caretakee dynamics                                                                                                   58
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences                                              57
Cuddling,Affection,Romance,Therapeutic sexual experiences                                                                                                 52
Cuddling,Sensual healing,Affection,Romance                                                                                                                47
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Energy work                                  45
Romance                                                                                                                                                   44
Cuddling,Affection                                                                                                                                        38
Clear, enthusiastic consent                                                                                                                               37
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                 35
Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                    34
Clear, enthusiastic consent,Cuddling                                                                                                                      33
Cuddling                                                                                                                                                  32
Clear, enthusiastic consent,Cuddling,Affection,Romance,Energy work                                                                                        31
Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences                                                                                 30
Clear, enthusiastic consent,Romance                                                                                                                       30
Clear, enthusiastic consent,Cuddling,Affection,Romance,Therapeutic sexual experiences,Energy work                                                         30
Clear, enthusiastic consent,Affection                                                                                                                     29
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance                                                                             27
Clear, enthusiastic consent,Cuddling,Tantra,Affection,Romance                                                                                             27
Clear, enthusiastic consent,Affection,Romance,Therapeutic sexual experiences                                                                              27
Clear, enthusiastic consent,Cuddling,Affection,Caretaker/caretakee dynamics                                                                               25
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Energy work,Caretaker/caretakee dynamics                                           23
Clear, enthusiastic consent,Cuddling,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                            23
Cuddling,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                    19
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Caretaker/caretakee dynamics                                                19
Cuddling,Sensual healing,Affection,Romance,Caretaker/caretakee dynamics                                                                                   19
Clear, enthusiastic consent,Affection,Romance,Caretaker/caretakee dynamics                                                                                19
Affection                                                                                                                                                 19
Clear, enthusiastic consent,Cuddling,Affection,Romance,Energy work,Caretaker/caretakee dynamics                                                           19
Clear, enthusiastic consent,Sensual healing,Affection,Romance                                                                                             19
Clear, enthusiastic consent,Cuddling,Tantra,Affection,Romance,Therapeutic sexual experiences                                                              18
Clear, enthusiastic consent,Affection,Caretaker/caretakee dynamics                                                                                        18
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance                                                                                              18
Clear, enthusiastic consent,Cuddling,Romance,Therapeutic sexual experiences                                                                               18
Clear, enthusiastic consent,Cuddling,Affection,Therapeutic sexual experiences                                                                             16
Clear, enthusiastic consent,Cuddling,Romance,Caretaker/caretakee dynamics                                                                                 16
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Energy work                                                                        16
Cuddling,Affection,Romance,Energy work                                                                                                                    15
Clear, enthusiastic consent,Therapeutic sexual experiences                                                                                                15
Cuddling,Romance,Therapeutic sexual experiences                                                                                                           14
Cuddling,Affection,Caretaker/caretakee dynamics                                                                                                           14
Affection,Romance,Therapeutic sexual experiences                                                                                                          14
Affection,Romance,Caretaker/caretakee dynamics                                                                                                            13
Caretaker/caretakee dynamics                                                                                                                              12
Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                                        11
Cuddling,Romance,Caretaker/caretakee dynamics                                                                                                             11
Cuddling,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                                                        11
Cuddling,Affection,Romance,Therapeutic sexual experiences,Energy work                                                                                     11
Romance,Therapeutic sexual experiences                                                                                                                    11
Therapeutic sexual experiences                                                                                                                            10
Cuddling,Caretaker/caretakee dynamics                                                                                                                     10
Clear, enthusiastic consent,Romance,Caretaker/caretakee dynamics                                                                                           9
Clear, enthusiastic consent,Cuddling,Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                 9
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection                                                                                             9
Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Energy work                                                                      9
Sensual healing,Affection,Romance,Therapeutic sexual experiences                                                                                           9
Clear, enthusiastic consent,Sensual healing,Affection,Romance,Therapeutic sexual experiences                                                               9
Cuddling,Affection,Therapeutic sexual experiences                                                                                                          9
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                   9
Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences                                                                           9
Clear, enthusiastic consent,Caretaker/caretakee dynamics                                                                                                   8
Clear, enthusiastic consent,Affection,Romance,Energy work                                                                                                  8
Clear, enthusiastic consent,Cuddling,Romance,Energy work                                                                                                   8
Cuddling,Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                             7
Clear, enthusiastic consent,Sensual healing,Affection,Romance,Caretaker/caretakee dynamics                                                                 7
Clear, enthusiastic consent,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                  7
Clear, enthusiastic consent,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                  7
Clear, enthusiastic consent,Cuddling,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                   7
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance,Therapeutic sexual experiences                                                                7
Cuddling,Tantra,Affection,Romance                                                                                                                          7
Clear, enthusiastic consent,Cuddling,Tantra,Affection,Romance,Caretaker/caretakee dynamics                                                                 7
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance,Caretaker/caretakee dynamics                                                                  7
Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                                  7
Clear, enthusiastic consent,Sensual healing,Affection                                                                                                      6
Clear, enthusiastic consent,Cuddling,Sensual healing                                                                                                       6
Romance,Caretaker/caretakee dynamics                                                                                                                       6
Cuddling,Therapeutic sexual experiences                                                                                                                    6
Cuddling,Sensual healing,Affection                                                                                                                         6
Cuddling,Sensual healing,Romance                                                                                                                           6
Clear, enthusiastic consent,Cuddling,Caretaker/caretakee dynamics                                                                                          5
Cuddling,Sensual healing,Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                             5
Clear, enthusiastic consent,Affection,Romance,Therapeutic sexual experiences,Energy work                                                                   5
Cuddling,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                               5
Clear, enthusiastic consent,Sensual healing,Caretaker/caretakee dynamics                                                                                   5
Clear, enthusiastic consent,Romance,Therapeutic sexual experiences                                                                                         5
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Caretaker/caretakee dynamics                                                                5
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                 5
Clear, enthusiastic consent,Sensual healing,Romance                                                                                                        5
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Energy work,Caretaker/caretakee dynamics                                     5
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Therapeutic sexual experiences                                                              5
Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                              5
Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Energy work                                                               5
Clear, enthusiastic consent,Affection,Therapeutic sexual experiences                                                                                       5
Clear, enthusiastic consent,Cuddling,Tantra,Affection                                                                                                      5
Clear, enthusiastic consent,Sensual healing,Tantra,Therapeutic sexual experiences                                                                          4
Clear, enthusiastic consent,Romance,Energy work                                                                                                            4
Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                              4
Sensual healing,Affection,Therapeutic sexual experiences                                                                                                   4
Clear, enthusiastic consent,Cuddling,Affection,Energy work                                                                                                 4
Cuddling,Romance,Energy work,Caretaker/caretakee dynamics                                                                                                  4
Clear, enthusiastic consent,Cuddling,Tantra,Romance                                                                                                        4
Sensual healing,Affection,Caretaker/caretakee dynamics                                                                                                     4
Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                                      4
Clear, enthusiastic consent,Sensual healing,Affection,Therapeutic sexual experiences                                                                       4
Affection,Romance,Energy work                                                                                                                              4
Sensual healing,Affection,Romance                                                                                                                          4
Clear, enthusiastic consent,Sensual healing,Affection,Caretaker/caretakee dynamics                                                                         4
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Energy work                                                                  4
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Romance,Therapeutic sexual experiences                                                         4
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                       4

In [7]:
df[['gentleness2most']].value_counts()

gentleness2most
Affection                         2211
Cuddling                          1730
Romance                           1626
Clear, enthusiastic consent       1405
Caretaker/caretakee dynamics       664
Therapeutic sexual experiences     359
Sensual healing                    189
Tantra                             167
Energy work                         50
Name: count, dtype: int64

In [53]:
df['Totalgentleness2'].value_counts(dropna=False)

Totalgentleness2
NaN    6810
4.0    2170
5.0    1772
3.0    1229
6.0    1180
7.0     795
2.0     563
8.0     405
1.0     292
9.0     287
Name: count, dtype: int64

### Personality Traits

In [54]:
df[['Which of the following is the most severe for you? (trspees)']].value_counts(dropna=False)

Which of the following is the most severe for you? (trspees)
nan                                                             10932
Anxiety                                                          1217
Depression                                                        781
ADHD                                                              687
Social anxiety                                                    508
Body Dysmorphia                                                   232
Autism                                                            165
OCD                                                               133
Borderline                                                        111
PTSD                                                               99
C-PTSD                                                             85
Substance Abuse Disorder                                           83
Bipolar II                                                         80
Bipolar I                                                          75
Depersonalization/derealization                                    71
Anorexia                                                           57
Disassociative Identity Disorder                                   50
Schizophrenia                                                      49
Bulimia                                                            46
Sociopathy                                                         42
Name: count, dtype: int64

In [10]:
df[['opennessvariable', 'consciensiousnessvariable', 'extroversionvariable', 'neuroticismvariable', 'agreeablenessvariable', 'powerlessnessvariable']].apply(pd.Series.value_counts).fillna(0).astype(int)

,opennessvariable,consciensiousnessvariable,extroversionvariable,neuroticismvariable,agreeablenessvariable,powerlessnessvariable
-9.0,0,0,0,0,0,120
-8.0,0,0,0,0,0,126
-7.0,0,0,0,0,0,199
-6.0,169,160,1094,247,204,283
-5.0,205,187,1385,337,223,388
-4.0,298,254,1734,467,368,680
-3.0,397,444,1829,528,394,1094
-2.0,659,738,1875,815,593,1340
-1.0,1114,1248,1730,1564,915,1498
0.0,1911,2410,1747,2542,2031,1680
1.0,2149,2703,1126,2582,1556,1598
2.0,2389,2587,963,2051,1529,1681
3.0,2237,2033,746,1456,1871,1378
4.0,2015,1494,604,1413,2603,1155
5.0,1203,792,402,962,1790,817
6.0,757,453,268,539,1426,580
7.0,0,0,0,0,0,398
8.0,0,0,0,0,0,281
9.0,0,0,0,0,0,207

### Preferred Emotional Experience

In [11]:
# 'Totalyoufeel', 'Totalotherfeel1' # Counts

df[['youfeelmost', 'otherfeel1most']].apply(pd.Series.value_counts).fillna(0).astype(int)

                                youfeelmost  otherfeel1most
Aigreté ou désir                          1               1
Ambivalence or disinterest               19              34
Anger or tension                        192             242
Calmness or serenity                    168             199
Cruelty or brutality                    130             191
Despair or horror                        15              19
Disgust or revulsion                      7              18
Eagerness or desire                    4974            4593
Embarrassment or shame                  111              82
Fear or trepidation                      33              30
Grief or regret                           5               6
Hate or disdain                          19              47
Hesitation or reluctance                 87              85
Humiliation or worthlessness            316             210
Irritation or annoyance                  55              98
Love or romance                        3004            2549
Numbness or disassociation               42              26
Power or smugness                       729            1742
Powerlessness or vulnerability         1739            1099
Safety or warmth                        978             918
Shock or surprise                       179             192
Shyness or nervousness                  313             486
Wildness or primalness                 1858            1767

In [12]:
df[['Check all that apply: Scenarios you find erotic tend to involve *you* feeling']].value_counts()

Check all that apply: Scenarios you find erotic tend to involve *you* feeling
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                 472
Eagerness or desire,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                      424
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                               318
Eagerness or desire,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                                       298
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                          294
Eagerness or desire,Wildness or primalness,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                247
Calmness or serenity,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                     198
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                                          181
Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                                          166
Eagerness or desire                                                                                                                                                                                                                                                                                                                                                                                                                                                                       165
Eagerness or desire,Wildness or primalness                                                                                                                                                                                                                                                                                                                                                                                                                                                152
Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                                                           138
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                  135
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                             126
Eagerness or desire,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                                                               123
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                           123
Eagerness or desire,Safety or warmth,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                                       121
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                        113
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                               107
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                102
Eagerness or desire,Wildness or primalness,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                               99
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                    98
Eagerness or desire,Safety or warmth,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                                     84
Eagerness or desire,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                                                                                 82
Eagerness or desire,Wildness or primalness,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                                               71
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Powerlessness or vulnerability,Power or smugness                                                                                                                                                                                                                                                                                                                                          69
Eagerness or desire,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                                                      69
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance,Powerlessness or vulnerability,Power or smugness                                                                                                                                                                                                                                                                                                                                                               68
Eagerness or desire,Safety or warmth,Love or romance,Shyness or nervousness,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                 66
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                     65
Eagerness or desire,Wildness or primalness,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                                  64
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Shock or surprise                                                                                                                                                                                                                                                                                                                                                                                                62
Eagerness or desire,Safety or warmth,Love or romance,Powerlessness or vulnerability,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                      61
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                            61
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                                         56
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shock or surprise                                                                                                                                                                                                                                                                                                                                                                         56
Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                                                               56
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance,Shock or surprise                                                                                                                                                                                                                                                                                                                                                                                              52
Eagerness or desire,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                                                         49
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness,Powerlessness or vulnerability,Shock or surprise                                                                                                                                                                                                                                                                                                                   49
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Powerlessness or vulnerability,Shock or surprise                                                                                                                                                                                                                                                                                                                                          47

In [13]:
df[['Check all that apply: Scenarios you find erotic tend to involve *the other person/people/creatures* feeling']].value_counts()

Check all that apply: Scenarios you find erotic tend to involve *the other person/people/creatures* feeling
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                 387
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                          381
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                               359
Eagerness or desire,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                      346
Eagerness or desire,Wildness or primalness,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                268
Eagerness or desire,Wildness or primalness,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                              250
Eagerness or desire,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                                       245
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                             238
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                        202
Calmness or serenity,Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                     202
Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                                                           178
Safety or warmth,Love or romance                                                                                                                                                                                                                                                                                                                                                                                                                                                          171
Eagerness or desire                                                                                                                                                                                                                                                                                                                                                                                                                                                                       159
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                   158
Eagerness or desire,Wildness or primalness                                                                                                                                                                                                                                                                                                                                                                                                                                                153
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                                          153
Eagerness or desire,Wildness or primalness,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                                              131
Eagerness or desire,Safety or warmth,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                                    123
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                               123
Eagerness or desire,Love or romance,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                                                     114
Eagerness or desire,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                                                               102
Eagerness or desire,Safety or warmth,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                                        95
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                                         84
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                     80
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                            80
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                 78
Eagerness or desire,Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                                                                      65
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shock or surprise                                                                                                                                                                                                                                                                                                                                                                         61
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                   60
Eagerness or desire,Safety or warmth,Love or romance,Shyness or nervousness,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                 57
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness,Powerlessness or vulnerability,Shock or surprise                                                                                                                                                                                                                                                                                                                   57
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                            54
Eagerness or desire,Calmness or serenity,Safety or warmth,Love or romance,Shock or surprise                                                                                                                                                                                                                                                                                                                                                                                                53
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shock or surprise,Power or smugness                                                                                                                                                                                                                                                                                                                                                       51
Eagerness or desire,Love or romance,Powerlessness or vulnerability                                                                                                                                                                                                                                                                                                                                                                                                                         51
Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness                                                                                                                                                                                                                                                                                                                                                                                                               49
Eagerness or desire,Wildness or primalness,Irritation or annoyance,Ambivalence or disinterest,Numbness or disassociation,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness,Powerlessness or vulnerability,Hesitation or reluctance,Shock or surprise,Fear or trepidation,Humiliation or worthlessness,Embarrassment or shame,Grief or regret,Despair or horror,Disgust or revulsion,Anger or tension,Hate or disdain,Cruelty or brutality,Power or smugness     49
Eagerness or desire,Wildness or primalness,Safety or warmth,Love or romance,Powerlessness or vulnerability,Power or smugness                                                                                                                                                                                                                                                                                                                                                               48
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness,Shock or surprise                                                                                                                                                                                                                                                                                                                                                  48
Eagerness or desire,Wildness or primalness,Calmness or serenity,Safety or warmth,Love or romance,Shyness or nervousness,Power or smugness                                                                                                                                                                                                                                                                                                                                                  48
Power or smugness                                                                                                                                                                                                                                                                                                                                                                                                                                                                          47

In [14]:
df[['Which of the following do you find erotic? (vqogs86)']].value_counts()

Which of the following do you find erotic? (vqogs86)
Clear, enthusiastic consent,Cuddling,Affection,Romance                                                                                                   781
Clear, enthusiastic consent,Cuddling,Affection,Romance,Caretaker/caretakee dynamics                                                                      252
Cuddling,Affection,Romance                                                                                                                               241
Clear, enthusiastic consent,Cuddling,Affection,Romance,Therapeutic sexual experiences                                                                    237
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance                                                                                   234
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences                                                    221
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                       204
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics    173
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics           121
Clear, enthusiastic consent,Cuddling,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                       115
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Caretaker/caretakee dynamics                                                      107
Clear, enthusiastic consent,Affection,Romance                                                                                                             88
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Energy work                                         78
Clear, enthusiastic consent,Cuddling,Romance                                                                                                              73
Affection,Romance                                                                                                                                         64
Clear, enthusiastic consent,Cuddling,Affection                                                                                                            64
Cuddling,Romance                                                                                                                                          58
Cuddling,Affection,Romance,Caretaker/caretakee dynamics                                                                                                   58
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences                                              57
Cuddling,Affection,Romance,Therapeutic sexual experiences                                                                                                 52
Cuddling,Sensual healing,Affection,Romance                                                                                                                47
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Energy work                                  45
Romance                                                                                                                                                   44
Cuddling,Affection                                                                                                                                        38
Clear, enthusiastic consent                                                                                                                               37
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                 35
Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                    34
Clear, enthusiastic consent,Cuddling                                                                                                                      33
Cuddling                                                                                                                                                  32
Clear, enthusiastic consent,Cuddling,Affection,Romance,Energy work                                                                                        31
Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences                                                                                 30
Clear, enthusiastic consent,Romance                                                                                                                       30
Clear, enthusiastic consent,Cuddling,Affection,Romance,Therapeutic sexual experiences,Energy work                                                         30
Clear, enthusiastic consent,Affection                                                                                                                     29
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance                                                                             27
Clear, enthusiastic consent,Cuddling,Tantra,Affection,Romance                                                                                             27
Clear, enthusiastic consent,Affection,Romance,Therapeutic sexual experiences                                                                              27
Clear, enthusiastic consent,Cuddling,Affection,Caretaker/caretakee dynamics                                                                               25
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Energy work,Caretaker/caretakee dynamics                                           23
Clear, enthusiastic consent,Cuddling,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                            23
Cuddling,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                    19
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Caretaker/caretakee dynamics                                                19
Cuddling,Sensual healing,Affection,Romance,Caretaker/caretakee dynamics                                                                                   19
Clear, enthusiastic consent,Affection,Romance,Caretaker/caretakee dynamics                                                                                19
Affection                                                                                                                                                 19
Clear, enthusiastic consent,Cuddling,Affection,Romance,Energy work,Caretaker/caretakee dynamics                                                           19
Clear, enthusiastic consent,Sensual healing,Affection,Romance                                                                                             19
Clear, enthusiastic consent,Cuddling,Tantra,Affection,Romance,Therapeutic sexual experiences                                                              18
Clear, enthusiastic consent,Affection,Caretaker/caretakee dynamics                                                                                        18
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance                                                                                              18
Clear, enthusiastic consent,Cuddling,Romance,Therapeutic sexual experiences                                                                               18
Clear, enthusiastic consent,Cuddling,Affection,Therapeutic sexual experiences                                                                             16
Clear, enthusiastic consent,Cuddling,Romance,Caretaker/caretakee dynamics                                                                                 16
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Romance,Energy work                                                                        16
Cuddling,Affection,Romance,Energy work                                                                                                                    15
Clear, enthusiastic consent,Therapeutic sexual experiences                                                                                                15
Cuddling,Romance,Therapeutic sexual experiences                                                                                                           14
Cuddling,Affection,Caretaker/caretakee dynamics                                                                                                           14
Affection,Romance,Therapeutic sexual experiences                                                                                                          14
Affection,Romance,Caretaker/caretakee dynamics                                                                                                            13
Caretaker/caretakee dynamics                                                                                                                              12
Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                                        11
Cuddling,Romance,Caretaker/caretakee dynamics                                                                                                             11
Cuddling,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                                                        11
Cuddling,Affection,Romance,Therapeutic sexual experiences,Energy work                                                                                     11
Romance,Therapeutic sexual experiences                                                                                                                    11
Therapeutic sexual experiences                                                                                                                            10
Cuddling,Caretaker/caretakee dynamics                                                                                                                     10
Clear, enthusiastic consent,Romance,Caretaker/caretakee dynamics                                                                                           9
Clear, enthusiastic consent,Cuddling,Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                 9
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection                                                                                             9
Cuddling,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Energy work                                                                      9
Sensual healing,Affection,Romance,Therapeutic sexual experiences                                                                                           9
Clear, enthusiastic consent,Sensual healing,Affection,Romance,Therapeutic sexual experiences                                                               9
Cuddling,Affection,Therapeutic sexual experiences                                                                                                          9
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                   9
Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences                                                                           9
Clear, enthusiastic consent,Caretaker/caretakee dynamics                                                                                                   8
Clear, enthusiastic consent,Affection,Romance,Energy work                                                                                                  8
Clear, enthusiastic consent,Cuddling,Romance,Energy work                                                                                                   8
Cuddling,Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                             7
Clear, enthusiastic consent,Sensual healing,Affection,Romance,Caretaker/caretakee dynamics                                                                 7
Clear, enthusiastic consent,Sensual healing,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                  7
Clear, enthusiastic consent,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                  7
Clear, enthusiastic consent,Cuddling,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                   7
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance,Therapeutic sexual experiences                                                                7
Cuddling,Tantra,Affection,Romance                                                                                                                          7
Clear, enthusiastic consent,Cuddling,Tantra,Affection,Romance,Caretaker/caretakee dynamics                                                                 7
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance,Caretaker/caretakee dynamics                                                                  7
Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                                  7
Clear, enthusiastic consent,Sensual healing,Affection                                                                                                      6
Clear, enthusiastic consent,Cuddling,Sensual healing                                                                                                       6
Romance,Caretaker/caretakee dynamics                                                                                                                       6
Cuddling,Therapeutic sexual experiences                                                                                                                    6
Cuddling,Sensual healing,Affection                                                                                                                         6
Cuddling,Sensual healing,Romance                                                                                                                           6
Clear, enthusiastic consent,Cuddling,Caretaker/caretakee dynamics                                                                                          5
Cuddling,Sensual healing,Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                             5
Clear, enthusiastic consent,Affection,Romance,Therapeutic sexual experiences,Energy work                                                                   5
Cuddling,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                               5
Clear, enthusiastic consent,Sensual healing,Caretaker/caretakee dynamics                                                                                   5
Clear, enthusiastic consent,Romance,Therapeutic sexual experiences                                                                                         5
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Caretaker/caretakee dynamics                                                                5
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                 5
Clear, enthusiastic consent,Sensual healing,Romance                                                                                                        5
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Energy work,Caretaker/caretakee dynamics                                     5
Clear, enthusiastic consent,Cuddling,Sensual healing,Affection,Therapeutic sexual experiences                                                              5
Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                              5
Cuddling,Sensual healing,Tantra,Affection,Romance,Therapeutic sexual experiences,Energy work                                                               5
Clear, enthusiastic consent,Affection,Therapeutic sexual experiences                                                                                       5
Clear, enthusiastic consent,Cuddling,Tantra,Affection                                                                                                      5
Clear, enthusiastic consent,Sensual healing,Tantra,Therapeutic sexual experiences                                                                          4
Clear, enthusiastic consent,Romance,Energy work                                                                                                            4
Affection,Romance,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                              4
Sensual healing,Affection,Therapeutic sexual experiences                                                                                                   4
Clear, enthusiastic consent,Cuddling,Affection,Energy work                                                                                                 4
Cuddling,Romance,Energy work,Caretaker/caretakee dynamics                                                                                                  4
Clear, enthusiastic consent,Cuddling,Tantra,Romance                                                                                                        4
Sensual healing,Affection,Caretaker/caretakee dynamics                                                                                                     4
Affection,Therapeutic sexual experiences,Caretaker/caretakee dynamics                                                                                      4
Clear, enthusiastic consent,Sensual healing,Affection,Therapeutic sexual experiences                                                                       4
Affection,Romance,Energy work                                                                                                                              4
Sensual healing,Affection,Romance                                                                                                                          4
Clear, enthusiastic consent,Sensual healing,Affection,Caretaker/caretakee dynamics                                                                         4
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Affection,Romance,Energy work                                                                  4
Clear, enthusiastic consent,Cuddling,Sensual healing,Tantra,Romance,Therapeutic sexual experiences                                                         4
Clear, enthusiastic consent,Cuddling,Sensual healing,Romance,Therapeutic sexual experiences,Energy work,Caretaker/caretakee dynamics                       4

### Kinks

In [15]:
df[['Which describes you best? (cvc5b81)']].value_counts()

Which describes you best? (cvc5b81)
Switch/equal/no preference             4354
Moderately submissive                  2767
Moderately dominant                    2261
Slightly submissive                    1763
Slightly dominant                      1476
Totally submissive                     1469
Totally dominant                       1005
Name: count, dtype: int64

In [16]:
df[['Of these options, which one is the most erotic? (35jn7ej)']].value_counts()

Of these options, which one is the most erotic? (35jn7ej)
Humiliation for sluttiness                                   620
Verbal degredation                                           525
Facesitting                                                  405
Cuckoldry                                                    381
Objectification                                              306
Defilement (to corrupt, dirty, violate)                      222
Writing on bodies                                            108
Insults                                                      107
Public humiliation                                            92
Photography/videography                                       86
Urine                                                         79
Humiliation for sexual inexperience                           78
Small penis humiliation                                       74
Forced consumption of desireable things                       55
Forced consumption of undesireable things                     26
Flaccid play                                                  25
Impotence                                                     22
Scat                                                          22
Castration                                                    16
Other body part humiliation                                   11
Religious humiliation                                          9
Name: count, dtype: int64

In [17]:
df[['Of these options, which one is the most erotic? (35jn7eo)']].value_counts()

Of these options, which one is the most erotic? (35jn7eo)
Forced orgasms                                               1177
Rapeplay                                                     1133
Struggling/fighting                                           527
Sexual slavery                                                400
Dub-consensual (unclear consent)                              399
Body control (directly controlling a body, e.g. voodoo)       289
Coercion/blackmail                                            266
Abductions/kidnappings                                        249
Frotteurism (e.g. humping in a crowded subway)                200
Forced nudity                                                 193
Weapon threats (e.g. gunplay)                                  90
Stalking                                                       78
Inebriation                                                    63
Wartime raids                                                  41
Slave auctions                                                 25
Sex trafficking                                                10
Name: count, dtype: int64

In [18]:
df[['Of these options, which one is the most erotic? (35jn7ew)']].value_counts()

Of these options, which one is the most erotic? (35jn7ew)
Physical struggle/overpowering (e.g., pinning)                                         1656
Breath play (choking, asphyxiation)                                                    1377
Orgasm overload                                                                        1330
Orgasm denial                                                                           858
Sexual training (e.g., to give deeper blowjobs)                                         668
Ownership                                                                               506
Marking as property (e.g., branding, collars)                                           400
Petplay (master/pet roleplay)                                                           377
World of femaledom                                                                      338
Disempowerment (stripping power away from a powerful person)                            185
Powerbottoming (enthusiastic submissive, often queer)                                   161
Internal Enslavement (behavioral restrictions are internally imposed/fully trained)      83
World of maledom                                                                         81
Sexual education                                                                         78
Service/utility submission (performing service tasks)                                    72
Behavioral restrictions (e.g. limits on speech)                                          64
Financial domination                                                                     37
Bootblacking (polishing shoes submissively)                                              10
Name: count, dtype: int64

#### Kink Specific

In [19]:
df[['Uncommon things: Check all the following categories that contain a thing that arouses you.']].value_counts()

Uncommon things: Check all the following categories that contain a thing that arouses you.
Age: nonstandard (age gaps, ageplay, unusual ages, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        975
Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            584
Bodily secretions (farts, squirt, urine, blood, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           551
Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          416
Genderplay (sissification, futa, crossdressing, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           375
Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              356
Abnormal bodies and body parts (massive bellies, tails/horns, giants, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     202
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   194
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 183
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Bodily secretions (farts, squirt, urine, blood, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  160
Bodily secretions (farts, squirt, urine, blood, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      157
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     127
Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         109
Bodily secretions (farts, squirt, urine, blood, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    103
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Genderplay (sissification, futa, crossdressing, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   87
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Bodily secretions (farts, squirt, urine, blood, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              85
Objects: nonstandard (hairbrushes, rope, cars, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      85
Abnormal bodies and body parts (massive bellies, tails/horns, giants, etc.),Age: nonstandard (age gaps, ageplay, unusual ages, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             84
Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        74
Bodily secretions (farts, squirt, urine, blood, etc.),Genderplay (sissification, futa, crossdressing, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      73
Genderplay (sissification, futa, crossdressing, etc.),Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         70
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Bodily secretions (farts, squirt, urine, blood, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            66
Transformations (growth/shrinking, bodyswapping, furries, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  64
Genderplay (sissification, futa, crossdressing, etc.),Transformations (growth/shrinking, bodyswapping, furries, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            61
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             56

In [52]:
# Family Based Kinks
df[['Of these options, which one is the most erotic? (35jn7ek)']].value_counts(dropna=False)

Of these options, which one is the most erotic? (35jn7ek)
nan                                                          14342
Mother and son                                                 358
Father and daughter                                            334
Mother and daughter/son together                               183
Mother and daughter                                            101
Mother/father together and daughter                             82
Father and son                                                  62
Father and daughter/son together                                31
Mother/father together and son                                  10
Name: count, dtype: int64

In [21]:
df[['nonconsent1most']].value_counts()

nonconsent1most
Forced orgasms                                             1177
Rapeplay                                                   1133
Struggling/fighting                                         527
Sexual slavery                                              400
Dub-consensual (unclear consent)                            399
Body control (directly controlling a body, e.g. voodoo)     289
Coercion/blackmail                                          266
Abductions/kidnappings                                      249
Frotteurism (e.g. humping in a crowded subway)              200
Forced nudity                                               193
Weapon threats (e.g. gunplay)                                90
Stalking                                                     78
Inebriation                                                  63
Wartime raids                                                41
Slave auctions                                               25
Sex trafficking                                              10
Name: count, dtype: int64

In [22]:
# Roles
df[['Which of the following roles are erotic?']].value_counts()

Which of the following roles are erotic?
Teachers                                                                                                                                                                                                                29
Atheletes,Babysitter,Catgirls,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Geishas,Librarians,Maids,Nuns,Nurses,Scientists,Strippers,Students,Teachers                                                20
Doctors,Teachers                                                                                                                                                                                                        19
Atheletes,Doctors,Teachers                                                                                                                                                                                              16
Atheletes,Babysitter,Catgirls,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Librarians,Maids,Nuns,Nurses,Scientists,Strippers,Students,Teachers                                                        16
Catgirls,Maids                                                                                                                                                                                                          14
Atheletes,Babysitter,Catboys,Catgirls,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Geishas,Gigolos,Gynecologists,Librarians,Maids,Nazis,Nuns,Nurses,Priests,Scientists,Strippers,Students,Teachers    14
Students,Teachers                                                                                                                                                                                                       11
Atheletes                                                                                                                                                                                                               11
Atheletes,Criminals,Teachers                                                                                                                                                                                            10
Maids                                                                                                                                                                                                                   10
Criminals,Doctors,Teachers                                                                                                                                                                                              10
Babysitter,Catgirls,Cheerleaders,Maids,Nurses,Students,Teachers                                                                                                                                                         10
Babysitter,Students,Teachers                                                                                                                                                                                             9
Criminals,Teachers                                                                                                                                                                                                       9
Doctors                                                                                                                                                                                                                  9
Babysitter,Teachers                                                                                                                                                                                                      9
Babysitter,Catgirls,Celebrities,Cheerleaders,Escorts/prostitutes,Maids,Nurses,Strippers,Students,Teachers                                                                                                                9
Atheletes,Criminals,Doctors,Teachers                                                                                                                                                                                     8
Atheletes,Celebrities,Doctors                                                                                                                                                                                            8
Maids,Teachers                                                                                                                                                                                                           8
Babysitter,Cheerleaders,Maids,Students,Teachers                                                                                                                                                                          8
Doctors,Nurses                                                                                                                                                                                                           8
Babysitter,Maids,Students,Teachers                                                                                                                                                                                       8
Catgirls                                                                                                                                                                                                                 8
Criminals                                                                                                                                                                                                                7
Atheletes,Criminals,Doctors                                                                                                                                                                                              7
Atheletes,Doctors                                                                                                                                                                                                        7
Maids,Students,Teachers                                                                                                                                                                                                  7
Atheletes,Doctors,Students,Teachers                                                                                                                                                                                      7
Catgirls,Students                                                                                                                                                                                                        7
Atheletes,Babysitter,Celebrities,Cheerleaders,Doctors,Escorts/prostitutes,Maids,Nurses,Strippers,Students,Teachers                                                                                                       7
Atheletes,Babysitter,Catgirls,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Geishas,Gynecologists,Librarians,Maids,Nazis,Nuns,Nurses,Priests,Scientists,Strippers,Students,Teachers                     7
Atheletes,Babysitter,Cheerleaders,Doctors,Escorts/prostitutes,Maids,Nurses,Strippers,Students,Teachers                                                                                                                   7
Atheletes,Celebrities                                                                                                                                                                                                    6
Doctors,Gynecologists,Teachers                                                                                                                                                                                           6
Doctors,Scientists,Teachers                                                                                                                                                                                              6
Babysitter,Doctors,Students,Teachers                                                                                                                                                                                     6
Babysitter,Catgirls,Cheerleaders,Librarians,Maids,Nuns,Nurses,Students,Teachers                                                                                                                                          6
Doctors,Students,Teachers                                                                                                                                                                                                6
Strippers                                                                                                                                                                                                                6
Students                                                                                                                                                                                                                 6
Babysitter,Cheerleaders,Doctors,Maids,Nurses,Students,Teachers                                                                                                                                                           6
Maids,Nurses                                                                                                                                                                                                             6
Atheletes,Teachers                                                                                                                                                                                                       6
Catgirls,Doctors,Maids,Nurses,Teachers                                                                                                                                                                                   6
Cheerleaders,Escorts/prostitutes,Maids,Nurses,Strippers,Students,Teachers                                                                                                                                                6
Atheletes,Babysitter,Catgirls,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Geishas,Gynecologists,Librarians,Maids,Nuns,Nurses,Scientists,Strippers,Students,Teachers                                   6
Atheletes,Babysitter,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Librarians,Maids,Nuns,Nurses,Scientists,Strippers,Students,Teachers                                                                  6
Atheletes,Babysitter,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Librarians,Maids,Nurses,Scientists,Strippers,Students,Teachers                                                                                   6
Celebrities,Teachers                                                                                                                                                                                                     5
Celebrities,Criminals,Teachers                                                                                                                                                                                           5
Atheletes,Celebrities,Criminals,Doctors,Teachers                                                                                                                                                                         5
Babysitter,Doctors,Maids,Students,Teachers                                                                                                                                                                               5
Doctors,Maids,Teachers                                                                                                                                                                                                   5
Escorts/prostitutes,Strippers                                                                                                                                                                                            5
Atheletes,Babysitter,Catgirls,Celebrities,Cheerleaders,Doctors,Escorts/prostitutes,Librarians,Maids,Nurses,Scientists,Strippers,Students,Teachers                                                                        5
Doctors,Gynecologists                                                                                                                                                                                                    5
Babysitter,Librarians,Maids,Students,Teachers                                                                                                                                                                            5
Babysitter,Cheerleaders,Maids,Nurses,Students,Teachers                                                                                                                                                                   5
Catgirls,Maids,Students                                                                                                                                                                                                  5
Babysitter,Catgirls,Cheerleaders,Maids,Nuns,Nurses,Students,Teachers                                                                                                                                                     5
Babysitter,Catgirls,Cheerleaders,Escorts/prostitutes,Maids,Nuns,Nurses,Strippers,Students,Teachers                                                                                                                       5
Catgirls,Cheerleaders,Maids                                                                                                                                                                                              5
Atheletes,Babysitter,Catgirls,Celebrities,Cheerleaders,Doctors,Escorts/prostitutes,Maids,Nuns,Nurses,Strippers,Students,Teachers                                                                                         5
Atheletes,Babysitter,Catboys,Catgirls,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Geishas,Gigolos,Gynecologists,Librarians,Maids,Nuns,Nurses,Priests,Scientists,Strippers,Students,Teachers           5
Atheletes,Babysitter,Celebrities,Cheerleaders,Escorts/prostitutes,Maids,Nurses,Strippers,Students,Teachers                                                                                                               5
Babysitter,Catgirls,Cheerleaders,Maids,Teachers                                                                                                                                                                          5
Babysitter,Cheerleaders,Maids,Nurses,Teachers                                                                                                                                                                            5
Atheletes,Babysitter,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Geishas,Librarians,Maids,Nuns,Nurses,Scientists,Strippers,Students,Teachers                                                          5
Criminals,Maids                                                                                                                                                                                                          4
Doctors,Gynecologists,Students,Teachers                                                                                                                                                                                  4
Criminals,Doctors,Students,Teachers                                                                                                                                                                                      4
Catgirls,Maids,Strippers                                                                                                                                                                                                 4
Doctors,Maids,Nurses,Strippers,Students,Teachers                                                                                                                                                                         4
Babysitter,Strippers,Students,Teachers                                                                                                                                                                                   4
Atheletes,Babysitter,Catgirls,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Gynecologists,Librarians,Maids,Nazis,Nuns,Nurses,Priests,Scientists,Strippers,Students,Teachers                             4
Babysitter,Doctors,Librarians,Maids,Nurses,Teachers                                                                                                                                                                      4
Atheletes,Students,Teachers                                                                                                                                                                                              4
Maids,Nurses,Strippers                                                                                                                                                                                                   4
Cheerleaders,Doctors,Maids,Nurses,Students,Teachers                                                                                                                                                                      4
Atheletes,Babysitter,Celebrities,Cheerleaders,Criminals,Doctors,Escorts/prostitutes,Gynecologists,Librarians,Maids,Nuns,Nurses,Priests,Scientists,Strippers,Students,Teachers                                            4
Babysitter,Doctors,Gynecologists,Students,Teachers                                                                                                                                                                       4
Babysitter,Cheerleaders,Strippers,Teachers                                                                                                                                                                               4
Atheletes,Criminals                                                                                                                                                                                                      4
Doctors,Nurses,Students,Teachers                                                                                                                                                                                         4
Atheletes,Babysitter,Celebrities,Cheerleaders,Escorts/prostitutes,Maids,Strippers,Students,Teachers                                                                                                                      4
Atheletes,Babysitter,Cheerleaders,Doctors,Maids,Nurses,Teachers                                                                                                                                                          4
Atheletes,Babysitter,Celebrities,Cheerleaders,Doctors,Librarians,Maids,Nurses,Strippers,Students,Teachers                                                                                                                4
Babysitter,Catgirls,Maids,Students,Teachers                                                                                                                                                                              4
Babysitter,Maids,Nurses,Students,Teachers                                                                                                                                                                                4

##### CGL Kinks

In [40]:
df[['Uncommon things: Check all the following categories that contain a thing that arouses you.']].value_counts()

Uncommon things: Check all the following categories that contain a thing that arouses you.
Age: nonstandard (age gaps, ageplay, unusual ages, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        975
Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            584
Bodily secretions (farts, squirt, urine, blood, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           551
Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          416
Genderplay (sissification, futa, crossdressing, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           375
Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              356
Abnormal bodies and body parts (massive bellies, tails/horns, giants, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     202
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   194
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 183
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Bodily secretions (farts, squirt, urine, blood, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  160
Bodily secretions (farts, squirt, urine, blood, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      157
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     127
Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         109
Bodily secretions (farts, squirt, urine, blood, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    103
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Genderplay (sissification, futa, crossdressing, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   87
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Bodily secretions (farts, squirt, urine, blood, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              85
Objects: nonstandard (hairbrushes, rope, cars, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      85
Abnormal bodies and body parts (massive bellies, tails/horns, giants, etc.),Age: nonstandard (age gaps, ageplay, unusual ages, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             84
Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        74
Bodily secretions (farts, squirt, urine, blood, etc.),Genderplay (sissification, futa, crossdressing, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      73
Genderplay (sissification, futa, crossdressing, etc.),Mental Alteration (hypnotism/mind control, amnesia, cocaine, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         70
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Bodily secretions (farts, squirt, urine, blood, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            66
Transformations (growth/shrinking, bodyswapping, furries, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  64
Genderplay (sissification, futa, crossdressing, etc.),Transformations (growth/shrinking, bodyswapping, furries, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            61
Age: nonstandard (age gaps, ageplay, unusual ages, etc.),Objects: nonstandard (hairbrushes, rope, cars, etc.),Reproduction (pregnancy, surrogacy, oviposition, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             56

In [36]:
df[['cgl']].value_counts(dropna=False)

cgl
NaN    11363
0.0     1295
1.0      744
3.0      606
2.0      597
4.0      488
5.0      410
Name: count, dtype: int64

In [72]:
df[['regression']].value_counts(dropna=False)

regression
NaN           11363
0.0            2164
1.0             671
2.0             468
3.0             367
4.0             258
5.0             212
Name: count, dtype: int64

In [73]:
df[['progression']].value_counts(dropna=False)

progression
NaN            11363
0.0             2324
1.0              631
2.0              528
3.0              328
4.0              181
5.0              148
Name: count, dtype: int64

In [74]:
df[['agegap']].value_counts(dropna=False)

agegap
NaN       11362
4.0        1135
3.0        1079
2.0         685
5.0         664
1.0         467
0.0         111
Name: count, dtype: int64

In [75]:
df[['older']].value_counts(dropna=False)

older
NaN      11362
0.0       2018
1.0        732
2.0        475
3.0        434
4.0        267
5.0        215
Name: count, dtype: int64

In [76]:
df[['roles']].value_counts(dropna=False)

roles
NaN      8764
4.0      1778
3.0      1770
5.0      1281
2.0      1013
1.0       654
0.0       243
Name: count, dtype: int64

# CGL Data Extractions

In [37]:
cgl_df = df.copy()
# cgl_df['cgl']=cgl_df['cgl'].fillna(0)

# cgl_df[['cgl']].fillna(0).value_counts() 
# cgl_df[cgl_df.cgl>0].info()
# Count of arousal scale in cgl interest field, including NaN values.
cgl_df.cgl.value_counts(dropna=False)

cgl
NaN    11363
0.0     1295
1.0      744
3.0      606
2.0      597
4.0      488
5.0      410
Name: count, dtype: int64

## Export

### Cleaning

In [64]:
df[['Which describes you best? (cvc5b81)']].value_counts(dropna=False)

Which describes you best? (cvc5b81)
Switch/equal/no preference             4354
Moderately submissive                  2767
Moderately dominant                    2261
Slightly submissive                    1763
Slightly dominant                      1476
Totally submissive                     1469
Totally dominant                       1005
nan                                     408
Name: count, dtype: int64

In [42]:
# Nonstandard age arousal field extraction based on a checklist of interests. 
# This is a bit hacky, but it allows us to extract a signal about nonstandard age arousal without relying on the direct "cgl" field
# May be underreported or misunderstood by respondents.
uncommon_col = 'Uncommon things: Check all the following categories that contain a thing that arouses you.'
target = 'Age: nonstandard (age gaps, ageplay, unusual ages, etc'

cgl_df['nonstandard_age_tag'] = np.where(
    cgl_df[uncommon_col].isna(), np.nan,
    cgl_df[uncommon_col].str.contains(target, regex=False, na=False).astype(float)
)

cgl_df['nonstandard_age_tag'].value_counts(dropna=False)

nonstandard_age_tag
0.0    6026
NaN    5259
1.0    4218
Name: count, dtype: int64

In [38]:
# Erotic role field extraction.
roles_col = 'Which of the following roles are erotic?'
roles_df = cgl_df[roles_col].str.get_dummies(sep=',')

# Optional: namespace columns to avoid collisions, then join back
roles_df = roles_df.add_prefix('role_')
cgl_df = cgl_df.join(roles_df)
cgL_role_list=cgl_df.filter(like='role_').columns.tolist()

# Review
cgl_df.filter(like='role_').apply(pd.Series.value_counts).astype(int)

,role_Atheletes,role_Babysitter,role_Catboys,role_Catgirls,role_Celebrities,role_Cheerleaders,role_Criminals,role_Doctors,role_Escorts/prostitutes,role_Geishas,role_Gigolos,role_Gynecologists,role_Librarians,role_Maids,role_Nazis,role_Nuns,role_Nurses,role_Priests,role_Scientists,role_Strippers,role_Students,role_Teachers
0,13202,12614,14952,13252,13732,12537,13922,12625,13504,14794,15326,14751,13350,11812,15259,14090,12256,14910,14183,12797,12233,11160
1,2301,2889,551,2251,1771,2966,1581,2878,1999,709,177,752,2153,3691,244,1413,3247,593,1320,2706,3270,4343

In [43]:
# Soft erotic field extraction.
soft_erotic_col = "Which of the following do you find erotic? (vqogs86)"
soft_erotic_df = cgl_df[soft_erotic_col].str.get_dummies(sep=",")
soft_erotic_df = (
    cgl_df[soft_erotic_col]
    .str.lower()
    .str.get_dummies(sep=",")
    .add_prefix("soft_erotic_")
)
soft_erotic_df = soft_erotic_df.add_prefix("soft_erotic_")
cgl_df = cgl_df.join(soft_erotic_df)
soft_erotic_list = cgl_df.filter(like="soft_erotic_").columns.tolist()

cgl_df.columns = cgl_df.columns.str.replace('soft_erotic_soft_erotic_', 'soft_erotic_', regex=False)
soft_erotic_list = cgl_df.filter(like="soft_erotic_").columns.tolist()

# Review
cgl_df.filter(like="soft_erotic_").apply(pd.Series.value_counts).fillna(0).astype(int)

,soft_erotic_ enthusiastic consent,soft_erotic_affection,soft_erotic_caretaker/caretakee dynamics,soft_erotic_clear,soft_erotic_cuddling,soft_erotic_energy work,soft_erotic_romance,soft_erotic_sensual healing,soft_erotic_tantra,soft_erotic_therapeutic sexual experiences
0,11700,11224,13849,11700,11280,14708,11168,13636,14897,13518
1,3803,4279,1654,3803,4223,795,4335,1867,606,1985

In [49]:
ocean_cols = [
    "opennessvariable",
    "consciensiousnessvariable",
    "extroversionvariable",
    "neuroticismvariable",
    "agreeablenessvariable",
    "powerlessnessvariable",
]

cgl_df[ocean_cols] = cgl_df[ocean_cols].astype(int)

cgl_df[ocean_cols].apply(pd.Series.value_counts)

,opennessvariable,consciensiousnessvariable,extroversionvariable,neuroticismvariable,agreeablenessvariable,powerlessnessvariable
-9,NaN,NaN,NaN,NaN,NaN,120
-8,NaN,NaN,NaN,NaN,NaN,126
-7,NaN,NaN,NaN,NaN,NaN,199
-6,169.0,160.0,1094.0,247.0,204.0,283
-5,205.0,187.0,1385.0,337.0,223.0,388
-4,298.0,254.0,1734.0,467.0,368.0,680
-3,397.0,444.0,1829.0,528.0,394.0,1094
-2,659.0,738.0,1875.0,815.0,593.0,1340
-1,1114.0,1248.0,1730.0,1564.0,915.0,1498
0,1911.0,2410.0,1747.0,2542.0,2031.0,1680
1,2149.0,2703.0,1126.0,2582.0,1556.0,1598
2,2389.0,2587.0,963.0,2051.0,1529.0,1681
3,2237.0,2033.0,746.0,1456.0,1871.0,1378
4,2015.0,1494.0,604.0,1413.0,2603.0,1155
5,1203.0,792.0,402.0,962.0,1790.0,817
6,757.0,453.0,268.0,539.0,1426.0,580
7,NaN,NaN,NaN,NaN,NaN,398
8,NaN,NaN,NaN,NaN,NaN,281
9,NaN,NaN,NaN,NaN,NaN,207

## Ready

In [50]:
# CGL Review
df[['cgl']].value_counts(dropna=False)

cgl
NaN    11363
0.0     1295
1.0      744
3.0      606
2.0      597
4.0      488
5.0      410
Name: count, dtype: int64

In [77]:
# Ready to go
cgl_df = cgl_df.rename(columns={
    "Which of the following is the most severe for you? (trspees)": "diagnosis",
    'Your sexual interests feel (44qhm16)': 'sexual_interest_variety',
    'Which describes you best? (cvc5b81)': 'ds_preference',
    })

cgL_role_list=cgl_df.filter(like='role_').columns.tolist()

cgl_df = cgl_df.rename(columns={
    c: c.replace('variable', '')
    for c in ocean_cols
})

ocean_cols = [c.removesuffix('variable') for c in ocean_cols]


final_col=[
    'age',
    'cgl',
    *ocean_cols,
    'diagnosis',
    'sexual_interest_variety',
    'ds_preference',
    'youfeelmost', 'otherfeel1most',
    'older',
    'agegap',
    'progression',
    'regression',
    'roles',
    'nonstandard_age_tag',
    *cgL_role_list,
    *soft_erotic_list,
    
]

In [78]:
# Export datasource with selected columns.
cgl_df[final_col].to_csv("../database/cgl_BKS_data.csv", index=False)